In [1]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig

In [2]:
# define matrix
A = array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])

In [3]:
print(A)

[[-2 -4  2]
 [-2  1  2]
 [ 4  2  5]]


In [4]:
# factorize
values, vectors = eig(A)

In [5]:
print(values)
print(vectors)

[-5.  3.  6.]
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]


In [6]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd

In [9]:
# define a matrix
A = array([
[3, 1, 1],[-1, 3, 1]])
print(A)

[[ 3  1  1]
 [-1  3  1]]


In [10]:
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[3.46410162 3.16227766]
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [11]:
# define a matrix
A = array([
[3, 1, 1],[-1, 3, 1]])
print(A)

[[ 3  1  1]
 [-1  3  1]]


In [13]:
import numpy as np
values1, vectors1 = eig(np.dot(A, A.T))

In [14]:
values1

array([12., 10.])

In [20]:
vectors1

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [15]:
values2, vectors2 = eig(np.dot(A.T, A))

In [16]:
values2

array([ 0., 10., 12.])

In [24]:
vectors2.T

array([[ 1.82574186e-01,  3.65148372e-01, -9.12870929e-01],
       [-8.94427191e-01,  4.47213595e-01,  5.07702013e-16],
       [-4.08248290e-01, -8.16496581e-01, -4.08248290e-01]])

In [18]:
sigma=np.diag(values1)

In [1]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 1],[0, 1],[-1, 1]])
print(A)

[[ 1  1]
 [ 0  1]
 [-1  1]]


In [2]:
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[-0.57735027 -0.70710678  0.40824829]
 [-0.57735027  0.         -0.81649658]
 [-0.57735027  0.70710678  0.40824829]]
[1.73205081 1.41421356]
[[-0. -1.]
 [-1. -0.]]


# dimensionality reduction

In [4]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

In [5]:
# define a matrix
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [6]:
# Singular-value decomposition
U, s, VT = svd(A)

In [11]:
s

array([9.69657342e+01, 7.25578339e+00, 5.82172067e-15])

In [7]:
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

In [9]:
Sigma

array([[9.69657342e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 7.25578339e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.82172067e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [8]:
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

In [10]:
Sigma

array([[9.69657342e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 7.25578339e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.82172067e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [12]:
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]

In [13]:
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [14]:
# transform
T = U.dot(Sigma)
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [15]:
T = A.dot(VT.T)
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


# truncated SVD

In [16]:
from numpy import array
from sklearn.decomposition import TruncatedSVD

In [17]:
# define array
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [19]:
# svd
svd = TruncatedSVD(n_components=3)
svd.fit(A)
result = svd.transform(A)
print(result)

[[ 1.85215775e+01  6.47697214e+00  2.22044605e-16]
 [ 4.98131001e+01  1.91182038e+00  1.33226763e-15]
 [ 8.11046228e+01 -2.65333138e+00  0.00000000e+00]]
