In [1]:
import numpy as np
import pandas as pd
import time
import sys

In [2]:
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

In [3]:
# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]   # The purpose of zip() is to map the similar index of multiple containers so that they can be used just using as single entity. 
print("python list took: ",(time.time()-start)*1000)

python list took:  3095.5262184143066


In [4]:
# numpy array
start= time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

numpy took:  399.40452575683594


In [8]:
l=range(1000)
print(sys.getsizeof(1)*len(l))  #getsizeof(an integer number)

28000


In [7]:
array=np.arange(1000)
print(array.size*array.itemsize)

8000


In [9]:
a=np.array([5,6,9])

In [10]:
a[0]

5

In [13]:
a.ndim  # single dim array

1

In [11]:
b=np.array([[1,2],[3,4],[5,6]])

In [12]:
b.ndim  # 2D array

2

In [14]:
a.itemsize

8

In [15]:
b.dtype

dtype('int64')

In [17]:
b=np.array([[1,2],[3,4],[5,6]],dtype=np.float)

In [19]:
b.itemsize

8

In [20]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [21]:
b.size

6

In [22]:
b.shape

(3, 2)

In [23]:
c=np.array([[1,2],[3,4],[5,6]],dtype=complex)

In [24]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [27]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [113]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [114]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [115]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.40026871 0.72456583]
 [0.23301464 0.8303514 ]]


In [29]:
l=range(5) # python
l

range(0, 5)

In [30]:
l[0]

0

In [31]:
l[4]

4

In [32]:
np.arange(1,5)  # 5 not included  numpy fn

array([1, 2, 3, 4])

In [33]:
np.arange(1,15,2) # step 2

array([ 1,  3,  5,  7,  9, 11, 13])

In [34]:
np.linspace(1,5,10) # 10 numbers b/w 1 & 5 linearly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [36]:
b=np.array([[1,2],[3,4],[5,6]])

In [37]:
b.shape

(3, 2)

In [38]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
b.ravel()  # flatten array

array([1, 2, 3, 4, 5, 6])

In [41]:
b  # original one  put it in a variable

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
d=b.ravel()

In [43]:
d

array([1, 2, 3, 4, 5, 6])

In [44]:
b.min()

1

In [45]:
b.max()

6

In [46]:
b.sum()

21

In [47]:
b.sum(axis=0) # column sum

array([ 9, 12])

In [48]:
b.sum(axis=1)  # row sum

array([ 3,  7, 11])

In [49]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [50]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.std(b)  # std dev

1.707825127659933

In [52]:
a=np.array([[1,2],[3,4]])

In [53]:
b=np.array([[5,6],[7,8]])

In [54]:
a

array([[1, 2],
       [3, 4]])

In [55]:
b

array([[5, 6],
       [7, 8]])

In [56]:
a+b

array([[ 6,  8],
       [10, 12]])

In [57]:
a*b   # eliment wise mult

array([[ 5, 12],
       [21, 32]])

In [58]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [59]:
a.dot(b)   # matrix multiplication

array([[19, 22],
       [43, 50]])

In [1]:
import numpy as np 
x = np.array([[1,2],[3,4]]) 

In [2]:
y = np.linalg.inv(x) # matrix inverse

In [3]:
print(x)

[[1 2]
 [3 4]]


In [4]:
print(y)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
print(np.dot(x,y))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [7]:
a = np.array([[1, 2], [3, 4]])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [10]:
a.T

array([[1, 3],
       [2, 4]])

In [60]:
n=[6,5,7]  # normal python array

In [61]:
n[0:1]

[6]

In [62]:
n[-1]   # last element

7

In [63]:
a=np.array([1,2,3,4])

In [64]:
a[0:2]

array([1, 2])

In [65]:
b=np.array([[3,4,5],[5,6,7],[8,9,1]])

In [66]:
b

array([[3, 4, 5],
       [5, 6, 7],
       [8, 9, 1]])

In [67]:
b[1,2]  # first row second element

7

In [68]:
b[0:2]  # 0th n first row

array([[3, 4, 5],
       [5, 6, 7]])

In [69]:
b[0:2,2] # take aove and take 2nd element

array([5, 7])

In [70]:
b[-1]   #  last row

array([8, 9, 1])

In [71]:
b[-1,0:2] 

array([8, 9])

In [72]:
b[:]  # all rows

array([[3, 4, 5],
       [5, 6, 7],
       [8, 9, 1]])

In [73]:
b[:,1:3]

array([[4, 5],
       [6, 7],
       [9, 1]])

In [75]:
for row in b:
    print(row)

[3 4 5]
[5 6 7]
[8 9 1]


In [76]:
for cell in b.flat:
    print(cell)

3
4
5
5
6
7
8
9
1


In [77]:
a=np.arange(6).reshape(3,2)

In [78]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [80]:
b=np.arange(6,12).reshape(3,2)

In [81]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [82]:
np.vstack((a,b))   # stack arrays on top

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [83]:
np.hstack((a,b)) 

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [84]:
c=np.arange(30).reshape(2,15)

In [85]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [87]:
np.hsplit(c,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [88]:
result=np.hsplit(c,3)

In [90]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [91]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [92]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [94]:
result1=np.vsplit(c,2)

In [95]:
result1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [96]:
result1[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [97]:
a=np.arange(12).reshape(3,4)

In [98]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
b=a>4

In [100]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
a[b]  # displays true elements

array([ 5,  6,  7,  8,  9, 10, 11])

In [102]:
a[b]=-1

In [103]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [104]:
a=np.arange(12).reshape(3,4)

In [105]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [106]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [108]:
for row in a.flatten():   # direct 
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [109]:
for x in np.nditer(a,order='C'):  # C order row wise Fortran order column wise
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [110]:
for x in np.nditer(a,order='F'):  # C order row wise Fortran order column wise
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [112]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
for x in np.nditer(a,order='F',flags=['external_loop']):  # 
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [11]:
from numpy import random

In [12]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.9306482 , 0.85805139, 0.91297855, 0.1458289 , 0.42950714],
       [0.73057237, 0.00883105, 0.31923159, 0.96842362, 0.74683399],
       [0.73887229, 0.81845791, 0.53675363, 0.34680166, 0.09442754],
       [0.71948318, 0.34408771, 0.04251569, 0.70428297, 0.68648357],
       [0.61204305, 0.49283346, 0.80645639, 0.45061099, 0.24261982]])

In [13]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.11208057, 0.9249093 , 0.14806448, 0.7457652 , 0.01905834],
       [0.66252282, 0.91015532, 0.72656955, 0.99636745, 0.61252628],
       [0.92563901, 0.82646036, 0.59511839, 0.87861387, 0.87383402],
       [0.29060052, 0.76655337, 0.46151813, 0.4350749 , 0.9953426 ],
       [0.83527423, 0.82533667, 0.00266061, 0.88914844, 0.14564725]])

In [15]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

# Linear Algebra

In [19]:
import numpy as np
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [20]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [21]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [23]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [24]:
np.diag(A, -1)

array([10, 21, 32, 43])

# We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [26]:
v1 = np.arange(0, 5)

In [29]:
v1 * 2

array([0, 2, 4, 6, 8])

In [30]:
v1 + 2

array([2, 3, 4, 5, 6])

In [32]:
A * 2

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [33]:
A + 2

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46]])

In [34]:
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]), array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

# Element-wise array-array operations

In [35]:
# When we add, subtract, multiply and divide arrays with each other, the default behaviour is element-wise operations:

In [36]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [37]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [38]:
# If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [39]:
A.shape, v1.shape

((5, 5), (5,))

In [40]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

# Matrix algebra

In [41]:
# What about matrix mutiplication? There are two ways. We can either use the dot function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [43]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [44]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [46]:
np.dot(v1, v1)

30

In [47]:
v1

array([0, 1, 2, 3, 4])

In [48]:
# Alternatively, we can cast the array objects to the type matrix. This changes the behavior of the standard arithmetic operators +, -, * to use matrix algebra.

In [50]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector

In [51]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [52]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [53]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [54]:
# inner product
v.T * v

matrix([[30]])

In [55]:
# with matrix objects, standard matrix algebra applies
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

In [56]:
# If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [58]:
v = np.matrix([1,2,3,4,5,6]).T

In [60]:
np.shape(M), np.shape(v)

((5, 5), (6, 1))

In [61]:
M * v

ValueError: shapes (5,5) and (6,1) not aligned: 5 (dim 1) != 6 (dim 0)

# Matrix computations

In [65]:
C=np.array([[1,2],[3,4]])

In [66]:
# Inverse
np.linalg.inv(C) # equivalent to C.I 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [69]:
np.linalg.det(C)

-2.0000000000000004

In [71]:
np.trace(C)

5