In [15]:
from array import *
import numpy as np
from numpy.linalg import eig
from scipy.linalg import svd
A=np.array([[3,1,1],[-1,3,1]])
values,vectors=eig(np.dot(A,A.T))
values1,vectors1=eig(np.dot(A.T,A))
print(vectors)
print(vectors1)
mat1,mat2,mat3=svd(A)
print(mat1)
print(mat2)
print(mat3)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 1.82574186e-01 -8.94427191e-01 -4.08248290e-01]
 [ 3.65148372e-01  4.47213595e-01 -8.16496581e-01]
 [-9.12870929e-01  5.07702013e-16 -4.08248290e-01]]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[3.46410162 3.16227766]
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.27355937e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]
